spring.application.name=corporation_database

spring.config.import=optional:file:.env[.properties]

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/corporation
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver